sudo: required
services:
    - docker

before_install:
    - docker build -t aelouarak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aelouarak/docker-react npm run test -- --coverage